### ISSUE TITLE
smarty字符的筛选

### ISSUE THREAD

**Issue by fengsx** [babyzone2004/fis-optimizer-htmlmin#1]
比如这句
![234](https://cloud.githubusercontent.com/assets/7709602/5886701/017f2c9a-a3e8-11e4-93a0-29aa3c914bb5.jpg)

让他压缩的时候，无视{if}这种，该怎么办？
那个英文的，实在太晦涩了，求教

**Comment by babyzone2004** [comment]
可使用customAttrSurround配置，详情：https://github.com/kangax/html-minifier/wiki/Minifying-Handlebars-templates

**Comment by babyzone2004** [comment]
customAttrSurround: [
                    [/{[^}]+}/, /{\/[^}]+}/]
 ]
注意标签直接两边内容不能有空格：{if $gender == 2}checked{/if}
